frontend/controllers/HomeController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use backend\models\MasterMobil;
use backend\models\MasterGallery;
use backend\models\MobilDokumen;
use backend\models\MasterPembelian;
use backend\models\MasterKonsumen;
use frontend\models\PesanForm;
use frontend\models\BlastForm;
use frontend\models\ReminderForm;
use yii\web\UploadedFile;
use yii\helpers\Url;

/**
 * Site controller
 */
class HomeController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        $this->layout = "@app/views/layouts/column1.php";

        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup','createantrian'],
                'rules' => [
                    [
                        'actions' => ['signup','createantrian'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */

    public function actionIndex()
    {
        // Yii::$app->user->isGuest;
        if (!Yii::$app->user->id) {
            // return $this->goHome();
            return $this->redirect(['site/login']);
        }

        return $this->render('index');
    }

    public function actionKendaraan()
    {
        $model = MasterMobil::find()->orderBy([
            'id' => SORT_DESC,
        ])->all();
        $jml_kendaraan = count($model);
        return $this->render('list_kendaraan', ['model' => $model, 'total' => $jml_kendaraan]);
    }

    public function actionNewvehicle()
    {
        $model = new MasterMobil();
        $modelGallery = new MasterGallery();

        if ($model->load(Yii::$app->request->post())) {

            /*$model->dok_stnk = UploadedFile::getInstance($model,'dok_stnk');
                $model->dok_bpkb = UploadedFile::getInstance($model,'dok_bpkb');
                $model->dok_faktur = UploadedFile::getInstance($model,'dok_faktur');
                $model->dok_copyktp_stnk = UploadedFile::getInstance($model,'dok_copyktp_stnk');
                $model->dok_surat_buka_blokir = UploadedFile::getInstance($model,'dok_surat_buka_blokir');
                $model->dok_pelepasan_hak = UploadedFile::getInstance($model,'dok_pelepasan_hak');
                $model->dok_kwitansi_blangko = UploadedFile::getInstance($model,'dok_kwitansi_blangko');
                $model->dok_ktp_penjual = UploadedFile::getInstance($model,'dok_ktp_penjual');
                $model->dok_foto_penjual = UploadedFile::getInstance($model,'dok_foto_penjual');
                $model->dok_nota_bon1 = UploadedFile::getInstance($model,'dok_nota_bon1');
                $model->dok_nota_bon2 = UploadedFile::getInstance($model,'dok_nota_bon2');
                $model->dok_nota_bon3 = UploadedFile::getInstance($model,'dok_nota_bon3');
                $model->dok_nota_bon4 = UploadedFile::getInstance($model,'dok_nota_bon4');
                $model->dok_nota_bon5 = UploadedFile::getInstance($model,'dok_nota_bon5');*/

            if ($model->validate()) {
                /*$name_dok_stnk = mt_rand(10,100).'_'.substr(md5(time()),0,5).'-'.$model->dok_stnk->baseName . '.' . $model->dok_stnk->extension;
                    $name_dok_bpkb = mt_rand(10,100).'_'.substr(md5(time()),0,5).'-'.$model->dok_bpkb->baseName . '.' . $model->dok_bpkb->extension;
                    $name_dok_faktur = mt_rand(10,100).'_'.substr(md5(time()),0,5).'-'.$model->dok_faktur->baseName . '.' . $model->dok_faktur->extension;
                    if ($model->dok_copyktp_stnk !== null) {
                        $name_dok_copyktp_stnk = mt_rand(10,100).'_'.substr(md5(time()),0,5).'-'.$model->dok_copyktp_stnk->baseName . '.' . $model->dok_copyktp_stnk->extension;
                    }
                    if ($model->dok_surat_buka_blokir !== null) {
                        $name_dok_surat_buka_blokir = mt_rand(10,100).'_'.substr(md5(time()),0,5).'-'.$model->dok_surat_buka_blokir->baseName . '.' . $model->dok_surat_buka_blokir->extension;
                    }
                    if ($model->dok_pelepasan_hak !== null) {
                        $name_dok_pelepasan_hak = mt_rand(10,100).'_'.substr(md5(time()),0,5).'-'.$model->dok_pelepasan_hak->baseName . '.' . $model->dok_pelepasan_hak->extension;
                    }
                    if ($model->dok_kwitansi_blangko !== null) {
                        $name_dok_kwitansi_blangko = mt_rand(10,100).'_'.substr(md5(time()),0,5).'-'.$model->dok_kwitansi_blangko->baseName . '.' . $model->dok_kwitansi_blangko->extension;
                    }
                    if ($model->dok_ktp_penjual !== null) {
                        $name_dok_ktp_penjual = mt_rand(10,100).'_'.substr(md5(time()),0,5).'-'.$model->dok_ktp_penjual->baseName . '.' . $model->dok_ktp_penjual->extension;
                    }
                    if ($model->dok_foto_penjual !== null) {
                        $name_dok_foto_penjual = mt_rand(10,100).'_'.substr(md5(time()),0,5).'-'.$model->dok_foto_penjual->baseName . '.' . $model->dok_foto_penjual->extension;
                    }
                    if ($model->dok_nota_bon1 !== null) {
                        $name_dok_nota_bon1 = mt_rand(10,100).'_'.substr(md5(time()),0,5).'-'.$model->dok_nota_bon1->baseName . '.' . $model->dok_nota_bon1->extension;
                    }

                    if ($model->dok_nota_bon2 !== null) {
                        $name_dok_nota_bon2 = mt_rand(10,100).'_'.substr(md5(time()),0,5).'-'.$model->dok_nota_bon2->baseName . '.' . $model->dok_nota_bon2->extension;
                    }
                    if ($model->dok_nota_bon3 !== null) {
                        $name_dok_nota_bon3 = mt_rand(10,100).'_'.substr(md5(time()),0,5).'-'.$model->dok_nota_bon3->baseName . '.' . $model->dok_nota_bon3->extension;
                    }
                    if ($model->dok_nota_bon4 !== null) {
                        $name_dok_nota_bon4 = mt_rand(10,100).'_'.substr(md5(time()),0,5).'-'.$model->dok_nota_bon4->baseName . '.' . $model->dok_nota_bon4->extension;
                    }
                    if ($model->dok_nota_bon5 !== null) {
                        $name_dok_nota_bon5 = mt_rand(10,100).'_'.substr(md5(time()),0,5).'-'.$model->dok_nota_bon5->baseName . '.' . $model->dok_nota_bon5->extension;
                    }

                    $model->dok_stnk->saveAs('uploads/mobil/' . $name_dok_stnk);
                    $model->dok_bpkb->saveAs('uploads/mobil/' . $name_dok_bpkb);
                    $model->dok_faktur->saveAs('uploads/mobil/' . $name_dok_faktur);

                    if ($model->dok_copyktp_stnk !== null) {
                        $model->dok_copyktp_stnk->saveAs('uploads/mobil/' . $name_dok_copyktp_stnk);
                    }
                    if ($model->dok_surat_buka_blokir !== null) {
                        $model->dok_surat_buka_blokir->saveAs('uploads/mobil/' . $name_dok_surat_buka_blokir);
                    }
                    if ($model->dok_pelepasan_hak !== null) {
                        $model->dok_pelepasan_hak->saveAs('uploads/mobil/' . $name_dok_pelepasan_hak);
                    }
                    if ($model->dok_kwitansi_blangko !== null) {
                        $model->dok_kwitansi_blangko->saveAs('uploads/mobil/' . $name_dok_kwitansi_blangko);
                    }
                    if ($model->dok_ktp_penjual !== null) {
                        $model->dok_ktp_penjual->saveAs('uploads/mobil/' . $name_dok_ktp_penjual);
                    }
                    if ($model->dok_foto_penjual !== null) {
                        $model->dok_foto_penjual->saveAs('uploads/mobil/' . $name_dok_foto_penjual);
                    }
                    if ($model->dok_nota_bon1 !== null) {
                        $model->dok_nota_bon1->saveAs('uploads/mobil/' . $name_dok_nota_bon1);
                    }

                    if ($model->dok_nota_bon2 !== null) {
                        $model->dok_nota_bon2->saveAs('uploads/mobil/' . $name_dok_nota_bon2);
                    }
                    if ($model->dok_nota_bon3 !== null) {
                        $model->dok_nota_bon3->saveAs('uploads/mobil/' . $name_dok_nota_bon3);
                    }
                    if ($model->dok_nota_bon4 !== null) {
                        $model->dok_nota_bon4->saveAs('uploads/mobil/' . $name_dok_nota_bon4);
                    }
                    if ($model->dok_nota_bon5 != null) {
                        $model->dok_nota_bon5->saveAs('uploads/mobil/' . $name_dok_nota_bon5);
                    }

                    $model->dok_stnk = $name_dok_stnk;
                    $model->dok_bpkb = $name_dok_bpkb;
                    $model->dok_faktur = $name_dok_faktur;

                    if ($model->dok_copyktp_stnk !== null) {

frontend/views/layouts/_sidebar.php
<?php 
use yii\helpers\Url;

?>
<!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3><img src="<?php echo \Yii::getAlias('@web').'/asset/images/logo-mblkarawangs_hdr.jpg' ?>" alt="" class="img img-fluid"></h3>
            </div>

            <ul class="list-unstyled components">
                <p class="tops_listn">menu</p>
                <li>
                    <a href="<?php echo Url::toRoute(['home/index']) ?>">DASHBOARD</a>
                </li>
                <?php if (!Yii::$app->user->isGuest): ?>
                <li>
                    <a href="<?php echo Url::toRoute(['home/newvehicle']) ?>">KENDARAAN BARU</a>
                </li>
                <li>
                    <a href="<?php echo Url::toRoute(['home/kendaraan']) ?>">UPDATE KENDARAAN</a>
                </li>
                <li>
                    <a href="<?php echo Url::toRoute(['home/antrianpesan']) ?>">ANTRIAN PESAN</a>
                </li>
                <li>
                    <a href="<?php echo Url::toRoute(['home/wabirthday']) ?>">PESAN ULANG TAHUN</a>
                </li>
                <li>
                    <a href="<?php echo Url::toRoute(['home/wareminder']) ?>">PESAN REMINDER</a>
                </li>
                <li>
                    <a href="<?php echo Url::toRoute(['home/wablast']) ?>">KIRIM MASAL</a>
                </li>
                <!-- <li>
                    <a href="<?php echo Url::toRoute(['home/antrianpesan']) ?>">ANTRIAN PESAN</a>
                </li> -->
                <li>
                    <a href="http://app.whatsez.id/v2/" target="_blank">KE WHATSEZ</a>
                </li>
                <!-- <li>
                    <a href="#">BACKUP DATABASE</a>
                </li> -->
                <li>
                    <a href="<?php echo Url::toRoute(['users/index']) ?>">LIST USER</a>
                </li>
                <?php endif; ?>
            </ul>

            <div class="blc-copyrights">
                <p>Copyright &copy; <?php echo date("Y") ?> - Mobil Karawang <br>
                All rights reserved</p>
            </div>
        </nav>

frontend/views/layouts/_top_contents.php
<?php 
use yii\helpers\Url;
use yii\helpers\Html;
?>
<section class="tops_head">
	<div class="inner">
		<div class="row">
			<div class="col-md-6">
				<div class="taglines_hd d-none d-sm-block"><img src="<?php echo \Yii::getAlias('@web').'/asset/images/slog-headers_mobilkar.jpg' ?>" alt="" class="img img-fluid"></div>
				<div class="d-block d-sm-none taglines_hd mx-auto">
					<img src="<?php echo \Yii::getAlias('@web').'/asset/images/logo-mblkarawangs_hdr.jpg' ?>" alt="" class="img img-fluid d-block mx-auto">
					<div class="py-1"></div>
					<!-- <img src="<?php echo \Yii::getAlias('@web').'/asset/images/tagline-lgo-mobiles.png' ?>" alt="" class="img img-fluid"> -->
				</div>
			</div>
			<div class="col-md-6">
				<div class="text-right bloc-right-logout">
					<!-- <a href="#">Logout</a> -->
					<ul class="list-inline">
					<?php 
					 if (Yii::$app->user->isGuest) { ?>
				        <li><a href="<?php echo Url::toRoute(['/site/login']) ?>">Login</a></li>
				    <?php } else {
				        $menuItems = '<li>'
				            . Html::beginForm(['/site/logout'], 'post')
				            . Html::submitButton(
				                'Logout (' . Yii::$app->user->identity->username . ')',
				                ['class' => 'btn btn-link logout']
				            )
				            . Html::endForm()
				            . '</li>';
				        echo $menuItems;
				    }
					?>
					</ul>
				</div>
			</div>
		</div>

		<div class="clear clearfix"></div>
	</div>

</section>

<div class="d-block d-sm-none">
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <a class="navbar-brand" href="#">MENU</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarNavDropdown">
	    <ul class="navbar-nav">
			<li class="nav-item">
				<a class="nav-link" href="<?php echo Url::toRoute(['home/index']) ?>">DASHBOARD</a>
			</li>
			<?php if (!Yii::$app->user->isGuest): ?>
			<li class="nav-item">
				<a class="nav-link" href="<?php echo Url::toRoute(['home/newvehicle']) ?>">KENDARAAN BARU</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="<?php echo Url::toRoute(['home/kendaraan']) ?>">UPDATE KENDARAAN</a>
			</li>
			<li class="nav-item">
					<a class="nav-link" href="<?php echo Url::toRoute(['home/antrianpesan']) ?>">ANTRIAN PESAN</a>
			</li>
			<li class="nav-item">
					<a class="nav-link" href="<?php echo Url::toRoute(['home/wabirthday']) ?>">PESAN ULANG TAHUN</a>
			</li>
			<li class="nav-item">
					<a class="nav-link" href="<?php echo Url::toRoute(['home/wareminder']) ?>">PESAN REMINDER</a>
			</li>
			<li class="nav-item">
					<a class="nav-link" href="<?php echo Url::toRoute(['home/wablast']) ?>">KIRIM MASAL</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="http://app.whatsez.id/v2/" target="_blank">KIRIM PESAN WA</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="<?php echo Url::toRoute(['users/index']) ?>">LIST USER</a>
			</li>
			<?php endif; ?>
	    </ul>
	  </div>
	</nav>
</div>

frontend/views/layouts/column1.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

    <div class="wrapper">
        
        <?= $this->render('_sidebar') ?>

        <!-- Page Content  -->
        <div id="content">
            <?= $this->render('_top_contents') ?>            
            <div class="inners_content">
                <?= $content ?>
            </div>

            <div class="clear clearfix"></div>
        </div>
    </div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']],
        ['label' => 'About', 'url' => ['/site/about']],
        ['label' => 'Contact', 'url' => ['/site/contact']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>